apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: node-ns
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: node
          image: docker.io/divinaboules/finalapp
          ports:
            - containerPort: 3000